# inventory/hosts.yaml
---
core-switch-01:
  hostname: 192.168.1.1
  groups:
    - cisco_ios

core-switch-02:
  hostname: 192.168.1.2
  groups:
    - cisco_ios

edge-router-01:
  hostname: 10.0.0.1
  groups:
    - cisco_xr

fw-01:
  hostname: 172.16.0.1
  data:
    platform: "fortinet" # 也可以在这里单独指定平台
